### ISSUE TITLE
Unable to run in blender 2.93

### ISSUE THREAD

**Issue by Noiseko** [denetii/io_thps_scene#14]
Hi, when I try and enable the addon within blender I get this error.
blender log [here](https://hastebin.com/efanozeyah.yaml)

`Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/home/tamago/.config/blender/2.93/scripts/addons/io_thps_scene/__init__.py", line 29, in register
    auto_load.register()
  File "/home/tamago/.config/blender/2.93/scripts/addons/io_thps_scene/auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "THUGMergedObjects" registration error: vertex_groups could not register
`

**Comment by denetii** [comment]
This has been resolved with 1bff66a3375026cbad13ddda4d7b8a09f7a17b6c - though I've not fully tested on 2.93 or 3.0, so I suspect there may be other bugs. You can at least activate it, and most functionality appears to be working.
