### ISSUE TITLE
Incompatible with Blender 2.80

### ISSUE THREAD

**Issue by djoslin0** [denetii/io_thps_scene#6]
The latest blender release introduced breaking changes to add-ons. This add-on no longer works on 2.80.
The following exception is printed to the console when trying to load the plugin:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\djoslin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_thps_scene\__init__.py", line 22, in <module>
    modules = developer_utils.setup_addon_modules(__path__, __name__, "bpy" in locals())
  File "C:\Users\djoslin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_thps_scene\developer_utils.py", line 39, in setup_addon_modules
    modules = import_submodules(names)
  File "C:\Users\djoslin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_thps_scene\developer_utils.py", line 30, in import_submodules
    modules.append(importlib.import_module("." + name, package_name))
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\djoslin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_thps_scene\import_nodes.py", line 11, in <module>
    from . scene_props import thug_empty_update
  File "C:\Users\djoslin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_thps_scene\scene_props.py", line 9, in <module>
    from . ui_draw import *
  File "C:\Users\djoslin\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_thps_scene\ui_draw.py", line 24, in <module>
    draw_stuff_display_list_id = bgl.glGenLists(1)
AttributeError: module 'bgl' has no attribute 'glGenLists'
```

**Comment by denetii** [comment]
This has now been resolved with the blender2.8 branch. That is compatible with most versions of 2.8, as well as the 2.9 release.
